#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 27 14:11:42 2019

@author: walther
"""
import numpy as np
import os


pfx='ps113'
pf="/home/walther/Documents/Instruments/GUVis_scripts/ShRad/data/%s/pangaea/"%(pfx)

version=str('Comment:\tVersion 2, 2019-02-20\n')
if pfx=='ps83':
    version+=str('Other Version:\tWitthuhn et al. 2017 (URL: https://doi.org/10.1594/PANGAEA.872377)\n')

parameters=str('Parameter(s):\tDATE/TIME (Date/Time) * GEOCODE * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de)\n'+
               '\tLATITUDE (Latitude) * GEOCODE * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de)\n'+
               '\tLONGITUDE (Longitude) * GEOCODE * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de)\n'+
               '\tALTITUDE [m] (Altitude) * GEOCODE * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de)\n'+
               '\tSpectral irradiance, downward at 305 nm [W/m**2/nm] (Ed_305) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 340 nm [W/m**2/nm] (Ed_340) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 380 nm [W/m**2/nm] (Ed_380) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 412 nm [W/m**2/nm] (Ed_412) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 443 nm [W/m**2/nm] (Ed_443) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 510 nm [W/m**2/nm] (Ed_510) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 610 nm [W/m**2/nm] (Ed_610) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 625 nm [W/m**2/nm] (Ed_625) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 665 nm [W/m**2/nm] (Ed_665) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 694 nm [W/m**2/nm] (Ed_694) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 750 nm [W/m**2/nm] (Ed_750) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 765 nm [W/m**2/nm] (Ed_765) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 875 nm [W/m**2/nm] (Ed_875) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 940 nm [W/m**2/nm] (Ed_940) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 1020 nm [W/m**2/nm] (Ed_1020) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 1245 nm [W/m**2/nm] (Ed_1245) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 1550 nm [W/m**2/nm] (Ed_1550) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward at 1640 nm [W/m**2/nm] (Ed_1640) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tShort-wave downward (GLOBAL) radiation [W/m**2] (SWD) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 305 nm [W/m**2/nm] (Ei_305) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 340 nm [W/m**2/nm] (Ei_340) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 380 nm [W/m**2/nm] (Ei_380) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 412 nm [W/m**2/nm] (Ei_412) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 443 nm [W/m**2/nm] (Ei_443) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 510 nm [W/m**2/nm] (Ei_510) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 610 nm [W/m**2/nm] (Ei_610) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 625 nm [W/m**2/nm] (Ei_625) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 665 nm [W/m**2/nm] (Ei_665) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 694 nm [W/m**2/nm] (Ei_694) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 750 nm [W/m**2/nm] (Ei_750) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 765 nm [W/m**2/nm] (Ei_765) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 875 nm [W/m**2/nm] (Ei_875) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 940 nm [W/m**2/nm] (Ei_940) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 1020 nm [W/m**2/nm] (Ei_1020) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 1245 nm [W/m**2/nm] (Ei_1245) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 1550 nm [W/m**2/nm] (Ei_1550) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, incident at 1640 nm [W/m**2/nm] (Ei_1640) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tDirect radiation [W/m**2] (DIR) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 305 nm [W/m**2/nm] (Ed-Ei_305) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 340 nm [W/m**2/nm] (Ed-Ei_340) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 380 nm [W/m**2/nm] (Ed-Ei_380) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 412 nm [W/m**2/nm] (Ed-Ei_412) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 443 nm [W/m**2/nm] (Ed-Ei_443) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 510 nm [W/m**2/nm] (Ed-Ei_510) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 610 nm [W/m**2/nm] (Ed-Ei_610) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 625 nm [W/m**2/nm] (Ed-Ei_625) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 665 nm [W/m**2/nm] (Ed-Ei_665) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 694 nm [W/m**2/nm] (Ed-Ei_694) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 750 nm [W/m**2/nm] (Ed-Ei_750) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 765 nm [W/m**2/nm] (Ed-Ei_765) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 875 nm [W/m**2/nm] (Ed-Ei_875) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 940 nm [W/m**2/nm] (Ed-Ei_940) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 1020 nm [W/m**2/nm] (Ed-Ei_1020) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 1245 nm [W/m**2/nm] (Ed-Ei_1245) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 1550 nm [W/m**2/nm] (Ed-Ei_1550) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tSpectral irradiance, downward - incident at 1640 nm [W/m**2/nm] (Ed-Ei_1640) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tDiffuse radiation [W/m**2] (DIF) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 340 nm (AOT_340) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 380 nm (AOT_380) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 412 nm (AOT_412) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 443 nm (AOT_443) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 510 nm (AOT_510) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 610 nm (AOT_610) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 625 nm (AOT_625) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 665 nm (AOT_665) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 694 nm (AOT_694) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 750 nm (AOT_750) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 765 nm (AOT_765) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 875 nm (AOT_875) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 940 nm (AOT_940) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 1020 nm (AOT_1020) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 1245 nm (AOT_1245) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 1550 nm (AOT_1550) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)\n'+
               '\tAerosol optical thickness at 1640 nm (AOT_1640) * PI: Deneke, Hartwig (https://orcid.org/0000-0001-8595-533X, hartwig.deneke@tropos.de) * METHOD: Ground-Based UV-Visble radiometer with BioSHADE accessory, GUVis-3511, BSI Inc. (URL: http://www.biospherical.com/images/pdf/guvis-3511.pdf)')
topheader='/*\n'+version+parameters+'\n*/\n'


ldir=np.sort(np.array(os.listdir(pf)))
flist=[]
for f in ldir:
    if f[-3:]=='tab':
        flist.append(f)
        

with open(pf+flist[0],'r') as txt:
    header=txt.readline()

newlines=[topheader,header]
for f in flist:
    with open(pf+f,'r') as txt:
        _=txt.readline()
        lines=txt.readlines()
    newlines+=lines
    
with open(pf+'upload/%s_GUVis.pangaea'%(pfx),'w') as txt:
    txt.writelines(newlines)
    
    